#ifndef REMOTECOMMUNICATIONLIBRARY_GLOBAL_H
#define REMOTECOMMUNICATIONLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef REMOTECOMMUNICATIONLIBRARY_LIB
# define REMOTECOMMUNICATIONLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define REMOTECOMMUNICATIONLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // REMOTECOMMUNICATIONLIBRARY_GLOBAL_H
